### ISSUE TITLE
Error in cell_cycle_calculating 

### ISSUE THREAD

**Issue by Zifeng-L** [lilab-bcb/pegasus#124]
Hi, here.
There was a error report about cell cycle calculating.
`pg.calc_signature_score(BL03, 'cell_cycle_human')`

```
2020-11-16 09:28:39,786 - pegasus.tools.signature_score - INFO - Loaded signatures from GMT file /cluster/home/zfli/anaconda2/envs/pegasus/lib/python3.7/site-packages/pegasuspy-1.0.0-py3.7-linux-x86_64.egg/pegasus/data_files/cell_cycle_human.gmt.
2020-11-16 09:28:39,788 - pegasus.tools.signature_score - INFO - Signature G1/S: 43 out of 43 genes are used in signature score calculation.
2020-11-16 09:28:39,814 - pegasus.tools.signature_score - INFO - Signature G2/M: 54 out of 54 genes are used in signature score calculation.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-21-ea0cee51c1a7> in <module>()
----> 1 pg.calc_signature_score(BL03, 'cell_cycle_human')

/cluster/home/zfli/anaconda2/envs/pegasus/lib/python3.7/site-packages/pegasusio/decorators.py in wrapper_timer(*args, **kwargs)
     10                 def wrapper_timer(*args, **kwargs):
     11                         start = time.perf_counter()
---> 12                         result = func(*args, **kwargs)
     13                         end = time.perf_counter()
     14                         message = f"Function '{func.__name__}' finished in {{:.{precision}f}}s.".format(end - start)

/cluster/home/zfli/anaconda2/envs/pegasus/lib/python3.7/site-packages/pegasuspy-1.0.0-py3.7-linux-x86_64.egg/pegasus/tools/signature_score.py in calc_signature_score(data, signatures, n_bins, show_omitted_genes, random_state)
    204                 maxvalues = values.max(axis = 1)
    205 
--> 206                 null_idx = _estimate_null(maxvalues)
    207                 cycle_idx = ~null_idx
    208 

/cluster/home/zfli/anaconda2/envs/pegasus/lib/python3.7/site-packages/pegasuspy-1.0.0-py3.7-linux-x86_64.egg/pegasus/tools/signature_score.py in _estimate_null(maxvalues, right_cutoff)
     99             peak_pos.append(i)
    100     #
--> 101     assert len(peak_pos) > 0
    102     if len(peak_pos) > 2:
    103         logger.warning("Interesting! We detected more than 2 peaks. If you have time, please contact Cumulus/Pegasus team to investigate this case.")

AssertionError: 
```

It seemed that there were more than 2 peaks. So I want to contact your team to investigate it.

**Comment by bli25** [comment]
@Zifeng1995 , thanks for reporting! Can you update with the latest Pegasus from github?  It should fix this issue.

**Comment by YichaoOU** [comment]
I installed the latest version (directly from github) and still have this issue?

```
(pegasus) [yli11@nodecn202 chenggrp_213991_10x]$ pegasus cluster -p 10 --correct-batch-effect --batch-group-by Source --louvain --umap aggr_data.zarr.zip example
2021-03-15 00:54:41,382 - pegasusio.readwrite - INFO - zarr file 'aggr_data.zarr.zip' is loaded.
2021-03-15 00:54:41,382 - pegasusio.readwrite - INFO - Function 'read_input' finished in 0.31s.
2021-03-15 00:54:41,382 - pegasus - INFO - Inputs are loaded.
2021-03-15 00:54:42,299 - pegasusio.qc_utils - INFO - After filtration, 13321 out of 24125 cell barcodes are kept in UnimodalData object mm10-rna.
2021-03-15 00:54:42,299 - pegasus.tools.preprocessing - INFO - Function 'filter_data' finished in 0.39s.
2021-03-15 00:54:43,278 - pegasus.tools.preprocessing - INFO - After filtration, 19855/31053 genes are kept. Among 19855 genes, 15723 genes are robust.
2021-03-15 00:54:43,278 - pegasus.tools.preprocessing - INFO - Function 'identify_robust_genes' finished in 0.98s.
2021-03-15 00:54:43,278 - pegasus.tools.preprocessing - INFO - Function '_run_filter_data' finished in 1.90s.

2021-03-15 00:54:43,278 - pegasus - INFO - Begin to analyze UnimodalData mm10-rna.
2021-03-15 00:54:44,214 - pegasus.tools.preprocessing - INFO - Function 'log_norm' finished in 0.94s.
Traceback (most recent call last):
  File "/home/yli11/.conda/envs/pegasus/bin/pegasus", line 11, in <module>
    sys.exit(main())
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/__main__.py", line 56, in main
    command.execute()
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/commands/Clustering.py", line 296, in execute
    run_pipeline(self.args["<input_file>"], self.args["<output_name>"], **kwargs)
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/pipeline/pipeline.py", line 438, in run_pipeline
    analyze_one_modality(unidata, f"{output_name}.{unidata.get_uid()}", is_raw, append_data, **kwargs)
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/pipeline/pipeline.py", line 33, in analyze_one_modality
    tools.set_group_attribute(unidata, kwargs["group_attribute"])
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/tools/batch_correction.py", line 74, in set_group_attribute
    assert attribute_string in data.obs.columns
AssertionError
(pegasus) [yli11@nodecn202 chenggrp_213991_10x]$ pegasus cluster -p 10 --correct-batch-effect --batch-group-by Source --louvain --umap aggr_data.zarr.zip example
2021-03-15 00:54:41,382 - pegasusio.readwrite - INFO - zarr file 'aggr_data.zarr.zip' is loaded.
2021-03-15 00:54:41,382 - pegasusio.readwrite - INFO - Function 'read_input' finished in 0.31s.
2021-03-15 00:54:41,382 - pegasus - INFO - Inputs are loaded.
2021-03-15 00:54:42,299 - pegasusio.qc_utils - INFO - After filtration, 13321 out of 24125 cell barcodes are kept in UnimodalData object mm10-rna.
2021-03-15 00:54:42,299 - pegasus.tools.preprocessing - INFO - Function 'filter_data' finished in 0.39s.
2021-03-15 00:54:43,278 - pegasus.tools.preprocessing - INFO - After filtration, 19855/31053 genes are kept. Among 19855 genes, 15723 genes are robust.
2021-03-15 00:54:43,278 - pegasus.tools.preprocessing - INFO - Function 'identify_robust_genes' finished in 0.98s.
2021-03-15 00:54:43,278 - pegasus.tools.preprocessing - INFO - Function '_run_filter_data' finished in 1.90s.

2021-03-15 00:54:43,278 - pegasus - INFO - Begin to analyze UnimodalData mm10-rna.
2021-03-15 00:54:44,214 - pegasus.tools.preprocessing - INFO - Function 'log_norm' finished in 0.94s.
Traceback (most recent call last):
  File "/home/yli11/.conda/envs/pegasus/bin/pegasus", line 11, in <module>
    sys.exit(main())
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/__main__.py", line 56, in main
    command.execute()
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/commands/Clustering.py", line 296, in execute
    run_pipeline(self.args["<input_file>"], self.args["<output_name>"], **kwargs)
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/pipeline/pipeline.py", line 438, in run_pipeline
    analyze_one_modality(unidata, f"{output_name}.{unidata.get_uid()}", is_raw, append_data, **kwargs)
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/pipeline/pipeline.py", line 33, in analyze_one_modality
    tools.set_group_attribute(unidata, kwargs["group_attribute"])
  File "/home/yli11/.conda/envs/pegasus/lib/python3.8/site-packages/pegasus/tools/batch_correction.py", line 74, in set_group_attribute
    assert attribute_string in data.obs.columns
AssertionError


```
